### ISSUE TITLE
ZF 3 roadmap discussion

### ISSUE THREAD

**Issue by wshafer** [reliv/Rcm#293]
Just wanted to leave this here so we can begin discussion on a shift to ZF 3. 

If I were do this I'd do this in sections. 

1) move plugins to their own repos, which are still sitting their blank (sorry bout that)

2) switch all factories to using container-interop which is compatible with ZF 2 and ZF 3

3) fix all "Config" getters to "config"

4) remove all ServiceManagerAware interfaces

5) update the event listeners to new event signature

6) update composer.json files with minimum dependencies and add config for the ZF component installer. 

Anything else I'm missing?

**Comment by rodmcnew** [comment]
Although these would be nice if someone wants to do them, I do not think they are strictly required for ZF3.

2) switch all factories to using container-interop which is compatible with ZF 2 and ZF 3
-The old service manager interface is still there I am guessing

3) fix all "Config" getters to "config"
-Could be solved with a simple alias

**Comment by rodmcnew** [comment]
I'd also like to point out that Zend no longer suggests installing the framework meta package. They suggest installing only the components you need.

It may be a good idea to simply get onto the ZF3 service manager as a first step before messing with the event manager and the MVC. I wonder if this is feasible?

**Comment by wshafer** [comment]
Absolutely feasible. ZF has back ported all the ZF 3 features and signatures to make the upgrade path doable.  Hence why I suggest doing this in pieces and in the order listed. Moving to the container-Interop will get you almost there for SM 3 all that would be left is Removing the ServiceManager aware interfaces and fixing the config getters (and any getters we jacked up ourselves)

**Comment by wshafer** [comment]
Btw, doctrine isn't ZF3 ready ATM either so a jump to ZF3 will be a bit difficult. Not impossible, I've already ported all the DB stuff to expressive so I can back port that over here if we want.

**Comment by rodmcnew** [comment]
I pretty much agree with this roadmap. The things I'm most interested are first are getting to the highest 2.* version of zend-mvc and getting to the highest 3.* version of zend-service-manager.

Here is our current list we use. (note zend-mvc is stuck on a lower version due to ServiceManagerAware warning).

    "zendframework/zend-authentication": "^2.5",
    "zendframework/zend-cache": "^2.5",
    "zendframework/zend-captcha": "^2.5",
    "zendframework/zend-config": "^2.5",
    "zendframework/zend-crypt": "^2.5",
    "zendframework/zend-db": "^2.5",
    "zendframework/zend-dom": "^2.5",
    "zendframework/zend-escaper": "^2.5",
    "zendframework/zend-eventmanager": "^2.5",
    "zendframework/zend-filter": "^2.5",
    "zendframework/zend-form": "^2.5",
    "zendframework/zend-http": "^2.5",
    "zendframework/zend-i18n": "^2.5",
    "zendframework/zend-i18n-resources": "^2.5",
    "zendframework/zend-inputfilter": "^2.5",
    "zendframework/zend-modulemanager": "^2.5",
    "zendframework/zend-mvc": "2.5.0",
    "zendframework/zend-navigation": "^2.5",
    "zendframework/zend-paginator": "^2.5",
    "zendframework/zend-permissions-acl": "^2.5",
    "zendframework/zend-servicemanager": "^2.5",
    "zendframework/zend-session": "^2.5",
    "zendframework/zend-stdlib": "^2.5",
    "zendframework/zend-text": "^2.5",
    "zendframework/zend-uri": "^2.5",
    "zendframework/zend-validator": "^2.5",
    "zendframework/zend-view": "^2.5",

**Comment by rodmcnew** [comment]
@wshafer Just to keep you informed, we are moving away from the zend-mvc package with the eventual goal of removing this package from composer.json. We prefer to write controllers with the Zend\Stratigility\MiddlewareInterface interface rather than with the the zend-mvc controller interface. 

We are also looking into defining modules the expressive way rather than by using the ZF3 module manager. Expressive modules only support config so any "onBootstrap" type things will need removed. These "onBoostrap" type things slow things down for every request and are not ideal for interoperability with other frameworks.

For people who want to use ZF3 zend-mvc and module manager packages:
-We should be able to still provide a ZF3 module file.
-ZF3 supports middleware routes from what I understand so our Zend\Stratigility\MiddlewareInterface controllers should still work in ZF3

Expressive modules :
https://zend-expressive.readthedocs.io/en/latest/cookbook/modular-layout/ 

https://github.com/zendframework/zend-stratigility/blob/master/src/MiddlewareInterface.php

**Comment by rodmcnew** [comment]
One more thing to note: The expressive skel app uses "config" while zf3 uses "Config". I don't think its worth changing everything to one or the other when we can just create an alias.

**Comment by jerv13** [comment]
We are moving to zend-expressive

**Comment by jerv13** [comment]
We are moving to zend-expressive
